### ISSUE TITLE
Route error

### ISSUE THREAD

**Issue by CobanF8** [MisterJulsen/Create-Train-Navigator#2]
**Version:**
 - Minecraft Version: [e.g. 1.19.2]
 - Forge Version [e.g. 43.3.0]
 - Mod Version [e.g. 0.3.0-beta-1.19.2]

**Describe the bug**
Happens randomly not sure why

**To Reproduce**
1. Select start and stop station
2. Click find route
3. See error

**Expected behavior**
Result

**Additional context**
Console report:
[01:34:50] [Navigator/INFO] [de.mr.cr.ModMain/]: Route calculated. Took 14ms.
[01:34:56] [Navigator/INFO] [de.mr.cr.ModMain/]: Graph generated. Took 10ms. Contains 76 nodes, 240 edges and 37 schedules. 1 train processed.
[01:34:56] [Navigator/ERROR] [de.mr.cr.ModMain/]: Navigation error: 
java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because the return value of "java.util.Map.get(Object)" is null
	at de.mrjulsen.crn.core.navigation.Graph.lambda$dijkstra$27(Graph.java:404) ~[createrailwaysnavigator-0.3.0-beta-1.19.2.jar%23143!/:0.3.0-beta-1.19.2] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at de.mrjulsen.crn.core.navigation.Graph.lambda$dijkstra$28(Graph.java:399) ~[createrailwaysnavigator-0.3.0-beta-1.19.2.jar%23143!/:0.3.0-beta-1.19.2] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.IdentityHashMap$EntrySpliterator.forEachRemaining(IdentityHashMap.java:1563) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at de.mrjulsen.crn.core.navigation.Graph.dijkstra(Graph.java:397) ~[createrailwaysnavigator-0.3.0-beta-1.19.2.jar%23143!/:0.3.0-beta-1.19.2] {re:classloading}
	at de.mrjulsen.crn.core.navigation.Graph.searchRoute(Graph.java:218) ~[createrailwaysnavigator-0.3.0-beta-1.19.2.jar%23143!/:0.3.0-beta-1.19.2] {re:classloading}
	at de.mrjulsen.crn.core.navigation.Graph.navigate(Graph.java:209) ~[createrailwaysnavigator-0.3.0-beta-1.19.2.jar%23143!/:0.3.0-beta-1.19.2] {re:classloading}
	at de.mrjulsen.crn.network.packets.cts.NavigationRequestPacket.lambda$handle$2(NavigationRequestPacket.java:76) ~[createrailwaysnavigator-0.3.0-beta-1.19.2.jar%23143!/:0.3.0-beta-1.19.2] {re:classloading}
	at java.lang.Thread.run(Thread.java:840) [?:?] {}

**Comment by blockninja124** [comment]
I'm also getting this error, but I don't have access to the server console to get the full message. (its on a public server I'm not an admin of). It happens for me every time in the server, no matter the stations. But I can't get it to happen in another (signleplayer) world. Same "Cannot invoke "java.util.Set.stream()" because the return value of "java.util.Map.get(Object)" is null"

Version 1.20.1 fabric-0.15.11 mod version 0.5.2-beta-fabric

Lots of other mods, but since OP didn't include a modlist its probably not an incompatibility? I can send a modlist if needed.

**Comment by CobanF8** [comment]
Solved after the last update. However as I observed, the source of the problem was existance of one train. When I exclude that train , it was all okay.

Edit 1: Oh and yeah I should have shared the modlist, sorry. Although, since it is all okay after update with more mods on my server before, I don't think it is an incompatibility problem.
