### ISSUE TITLE
ClassCastException when Rendering Passenger Information Block in Create Railways Navigator

### ISSUE THREAD

**Issue by INV-PLA** [MisterJulsen/Create-Train-Navigator#69]
Bug Report

Version:

Minecraft Version: 1.20.1
Forge Version: 47.3.12
Mod Version: Create Railways Navigator 1.20.1-beta-0.7.1
Describe the bug:
When attempting to render a block entity related to Passenger Information, the game crashes due to a ClassCastException. Specifically, the class PassengerInformationScrollingTextSettings is being incorrectly cast to PassengerInformationDetailedSettings, causing the game to crash.

To Reproduce:

Place a Passenger Information block in the world.
Configure the block with a scrolling text setting.
Reload the chunk or view the block.
The game crashes with a ClassCastException.
Expected behavior:
The block entity should render correctly without causing the game to crash, regardless of the selected settings type.

Crash Log:
Attached below is the relevant portion of the crash log:

arduino
复制代码
java.lang.ClassCastException: class de.mrjulsen.crn.block.display.properties.PassengerInformationScrollingTextSettings cannot be cast to class de.mrjulsen.crn.block.display.properties.PassengerInformationDetailedSettings
	at de.mrjulsen.crn.client.ber.variants.BERPassengerInfoInformative.renderHeader(BERPassengerInfoInformative.java:179)
	...
Screenshots:
If applicable, attach screenshots of the block setup or the error.

Additional context:

The issue may be related to an internal misconfiguration or a compatibility issue with DragonLib (v1.20.1-2.2.22).
This issue occurs consistently with specific block configurations.
Thank you for your help!

**Comment by MisterJulsen** [comment]
Can you also send your modlist from the crash report please? For the versions of the other mods that were loaded

**Comment by INV-PLA** [comment]
[2024-12-19-4.log.gz](https://github.com/user-attachments/files/18206268/2024-12-19-4.log.gz)
[crash-2024-12-19_16.11.53-client.txt](https://github.com/user-attachments/files/18206273/crash-2024-12-19_16.11.53-client.txt)

**Comment by INV-PLA** [comment]
> Can you also send your modlist from the crash report please? For the versions of the other mods that were loaded

[2012月2024 15:05:23.151] [CRN Train Listener/ERROR] [DragonLib/]: Cannot run train listener task 'TrainListener#CreateTrainPredictionEvent': Cannot read field "entries" because the return value of "com.simibubi.create.content.trains.schedule.ScheduleRuntime.getSchedule()" is null
java.lang.NullPointerException: Cannot read field "entries" because the return value of "com.simibubi.create.content.trains.schedule.ScheduleRuntime.getSchedule()" is null
	at de.mrjulsen.crn.data.train.TrainListener.lambda$init$12(TrainListener.java:128) ~[createrailwaysnavigator-forge-1.20.1-beta-0.7.1.jar%23243!/:?]
	at de.mrjulsen.crn.data.train.TrainListener.lambda$start$14(TrainListener.java:189) ~[createrailwaysnavigator-forge-1.20.1-beta-0.7.1.jar%23243!/:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by MisterJulsen** [comment]
should be fixed in the new version 0.7.2
